name: Deploy Project
on:
  push:
    branches:
        - main
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: install dependencies
        run: npm ci
      - name: Lint the code
        run: npm lint
      - name: Test the code
        run: npm test
      - name: Build the code
        run: npm build